# SPDX-License-Identifier: Apache-2.0
name: "ZXF: Snyk Monitor"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  snyk:
    name: Snyk Monitor
    runs-on: hl-cn-snyk-check-lin

    steps:
      - name: Prepare Runner
        id: prepare-runner
        uses: pandaswhocode/initialize-github-job@c392c3e699995ab6030915302d2fc9bffb1e861f # v1.1.0
        with:
          checkout: "true"
          checkout-fetch-depth: 1
          checkout-token: "${{ github.token }}"
          setup-java: "true"
          java-distribution: "temurin"
          java-version: "25.0.2"
          setup-gradle: "true"
          setup-node: "true"
          node-version: "20"

      - name: Compile
        run: ./gradlew assemble

      - name: Setup Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: npm install -g snyk

      - name: Run Snyk Monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --subProject=aggregation --configuration-matching=mainRuntimeClasspath --policy-path=.snyk --trust-policies --org=hiero-consensus-node
